openapi: 3.0.0
info:
  description: yummly API
  title: yummly API
  version: v1
  x-sla: >-
    http://repo.designer.governify.io:10880/antgamdia/api_modeling_paper/modeling/yummly/plans.oai-at?accessToken=165a1761634db1e9bd304ea6f3ffcf2b
externalDocs:
  url: 'https://developer.yummly.com/documentation'
paths:
  /v1/api/metadata/ingredient:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /v1/api/metadata/allergy:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /v1/api/metadata/diet:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /v1/api/metadata/cuisine:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /v1/api/metadata/course:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /v1/api/metadata/holiday:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /v1/api/recipes:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  '/v1/api/recipe/{recipe-id}':
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
components:
  requestBodies:
    someRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/someRequestBody'
      required: true
  securitySchemes: {}
  schemas:
    someRequestBody: {}
    someResponseBody: {}
