openapi: 3.0.0
info:
  description: faceplusplus API
  title: faceplusplus API
  version: v1
  x-sla: >-
    http://repo.designer.governify.io:10880/antgamdia/api_modeling_paper/modeling/faceplusplus/plans.oai-at?accessToken=165a1761634db1e9bd304ea6f3ffcf2b
externalDocs:
  url: 'https://eversign.com/api/documentation/methods'
paths:
  /AddImage:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Compare:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /CreateAlbum:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /DeleteAlbum:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /DeleteFace:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Detect:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceAnalyze:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceGetDetail:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceSetAddface:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceSetAsyncAddFace:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceSetAsyncRemoveFace:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceSetCreate:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceSetDelete:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceSetGetdetail:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceSetGetFaceSets:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceSetGetFaceTaskStatus:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceSetRemoveFace:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceSetUpdate:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FaceSetUserID:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /FindCandidate:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /GetAlbumDetail:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /GetFaceDetail:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /GetImageDetail:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /GroupFace:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /GroupFaceTaskQuery:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /HumanBodyDetect:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /HumanBodyGesture:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /HumanBodySegment:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /MergeFace:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Search:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /SearchImage:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /SearchImageTaskQuery:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /SkeletonDetect:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /UpdateFace:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
components:
  requestBodies:
    someRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/someRequestBody'
      required: true
  securitySchemes: {}
  schemas:
    someRequestBody: {}
    someResponseBody: {}
