openapi: 3.0.0
info:
  description: sportradar API
  title: sportradar API
  version: v1
  x-sla: >-
    http://repo.designer.governify.io:10880/antgamdia/api_modeling_paper/modeling/sportradar/plans.oai-at?accessToken=165a1761634db1e9bd304ea6f3ffcf2b
externalDocs:
  url: 'https://developer.sportradar.com/io-docs'
paths:
  /NFL:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /MLB:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /NBA:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /NHL:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /NCAA-FB:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /NCAA-MB:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Golf:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /NASCAR:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Soccer-Europe:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Soccer-Americas:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Soccer-International:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Soccer-Asia:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Soccer-Other:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /NCAA-WB:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /NCAA-MH:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /WNBA:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /NBA-G-League:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Cricket:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Rugby:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Tennis:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  '/Counter-Strike:-Global-Offensive':
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /League-of-Legends:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /DOTA2:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Olympics:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Arena-Football-League:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Australian-Football:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Badminton:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Bandy:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Beach-Soccer:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Beach-Volleyball:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Curling:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Cycling:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Darts:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Field-Hockey:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Floorball:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Formula-1:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Formula-E:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Futsal:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Global-American-Football:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Global-Baseball:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Global-Basketball:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Global-Ice-Hockey:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Handball:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Indoor-Volleyball:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /IndyCar:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /MotoGP:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Motorsports:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Odds:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Pesapallo:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Snooker:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Squash:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /UFC:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Waterpolo:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
components:
  requestBodies:
    someRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/someRequestBody'
      required: true
  securitySchemes: {}
  schemas:
    someRequestBody: {}
    someResponseBody: {}
