openapi: 3.0.0
info:
  description: moz API
  title: moz API
  version: v1
  x-sla: >-
    http://repo.designer.governify.io:10880/antgamdia/api_modeling_paper/modeling/moz/plans.oai-at?accessToken=165a1761634db1e9bd304ea6f3ffcf2b
externalDocs:
  url: 'https://moz.com/products/api/pricing'
paths:
  /URLMetrics:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /Links:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /TopPages:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
  /AnchorText:
    get:
      description: Something
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/someResponseBody'
components:
  requestBodies:
    someRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/someRequestBody'
      required: true
  securitySchemes: {}
  schemas:
    someRequestBody: {}
    someResponseBody: {}
